-- Bright Path — conflict-safe lesson booking schema.
-- Hand-written (not generated by an ORM): the tutor/room/student overlap guarantee
-- lives in EXCLUDE constraints, which Prisma/most ORMs cannot express.
-- Meant to run once against a fresh database (see README). To start over,
-- `docker compose down -v` wipes the volume before re-running `npm run migrate`.

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE tutor (
  id      text PRIMARY KEY,   -- natural key from tutors.csv ("T1", "T2", ...) — already stable, no reason to invent a surrogate id
  name    text NOT NULL,
  subject text NOT NULL,
  phone   text
);

CREATE TABLE room (
  id   text PRIMARY KEY,      -- natural key ("R1".."R6")
  name text NOT NULL
);

CREATE TABLE student (
  id   uuid PRIMARY KEY,      -- the export has no student id; the seed script generates one per person it can tell apart
  name text NOT NULL          -- not unique: a name is not an identity, just a label. The live API never looks a
                               -- student up by name — see DECISIONS.md ("what is weak") for the seed-only exception.
);

CREATE TYPE lesson_kind AS ENUM ('single', 'exam_pair');
CREATE TYPE lesson_status AS ENUM ('booked', 'cancelled', 'no_show');

CREATE TABLE lesson (
  id           uuid PRIMARY KEY,
  tutor_id     text NOT NULL REFERENCES tutor(id),
  room_id      text NOT NULL REFERENCES room(id),
  starts_at    timestamptz NOT NULL,
  ends_at      timestamptz NOT NULL,
  kind         lesson_kind NOT NULL DEFAULT 'single',
  status       lesson_status NOT NULL DEFAULT 'booked',
  cancelled_at timestamptz,
  note         text,
  legacy_ref   text UNIQUE,   -- "L001".. for rows loaded from the export; NULL for lessons created through the API
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  CHECK (ends_at > starts_at),
  CHECK (cancelled_at IS NULL OR status = 'cancelled'),

  -- "a tutor can only be in one room at a time". A no-show still occupies the slot
  -- ("frees neither") — only a cancelled lesson frees it, hence status <> 'cancelled'
  -- rather than status = 'booked'.
  EXCLUDE USING gist (tutor_id WITH =, tstzrange(starts_at, ends_at) WITH &&) WHERE (status <> 'cancelled'),
  -- "a room holds one lesson at a time, whoever is teaching in it"
  EXCLUDE USING gist (room_id WITH =, tstzrange(starts_at, ends_at) WITH &&) WHERE (status <> 'cancelled')
);

CREATE TABLE lesson_student (
  lesson_id  uuid NOT NULL REFERENCES lesson(id),
  student_id uuid NOT NULL REFERENCES student(id),
  -- Denormalized copy of lesson.(starts_at, ends_at, status): EXCLUDE needs the range
  -- on the same table as the column it excludes on, and student_id only lives here.
  -- The app must keep this in sync on create/move/cancel/no-show — see DECISIONS.md.
  starts_at timestamptz NOT NULL,
  ends_at   timestamptz NOT NULL,
  status    lesson_status NOT NULL,

  PRIMARY KEY (lesson_id, student_id),
  -- "That can never happen again" (owner, re: a student booked in two places at once)
  EXCLUDE USING gist (student_id WITH =, tstzrange(starts_at, ends_at) WITH &&) WHERE (status <> 'cancelled')
);

CREATE TYPE lesson_event_type AS ENUM ('created', 'moved', 'cancelled', 'no_show');

CREATE TABLE lesson_event (
  id           uuid PRIMARY KEY,
  lesson_id    uuid NOT NULL REFERENCES lesson(id),
  occurred_at  timestamptz NOT NULL,
  type         lesson_event_type NOT NULL,
  before       jsonb,
  after        jsonb NOT NULL,
  after_cutoff boolean NOT NULL,
  actor        text NOT NULL   -- 'mai' (every API call — the tool is single-user) or 'seed'
);

CREATE TABLE legacy_conflict (
  id         uuid PRIMARY KEY,
  legacy_ref text NOT NULL,
  reason     text NOT NULL,    -- "tutor" | "room" | "student" — which exclusion rejected it at seed time
  raw_row    jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
